name: Python package

on:
  push:
  pull_request:
  merge_group:
    types: [checks_requested]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: test
        run: |
          pip install pytest pytest-cov
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest ./tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Check package version in setup.py and compare with master
        run: |
          cat setup.py | grep version
          git fetch origin master
          git diff --exit-code origin/master setup.py
          
          if [ $? -eq 0 ]; then
              echo "Error: Version in setup.py must be different from master"
              exit 1
          else
              echo "Version change detected - OK"
          fi